name: Build and Test

on:
  push:
    branches: [ main, develop, makeup-artist ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build project
      run: |
        xcodebuild clean build \
          -project TripCost.xcodeproj \
          -scheme TripCost \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Run tests (if available)
      run: |
        xcodebuild test \
          -project TripCost.xcodeproj \
          -scheme TripCost \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO || true
      continue-on-error: true
